train_dataset:
  name: dataset.data_val.PolypObjDataset
  params:
    image_root: 'media/dataset/COD10K/TrainDataset/Image/'
    gt_root: 'media/dataset/COD10K/TrainDataset/GT/'
    trainsize: 352

test_dataset:
  COD10K:
    name: dataset.data_val.test_dataset
    params:
      image_root: 'media/dataset/COD10K/TestDataset/COD10K/Image/'
      gt_root: 'media/dataset/COD10K/TestDataset/COD10K/GT/'
      testsize: 352
  CAMO:
    name: dataset.data_val.test_dataset
    params:
      image_root: 'media/dataset/COD10K/TestDataset/CAMO/Image/'
      gt_root: 'media/dataset/COD10K/TestDataset/CAMO/GT/'
      testsize: 352
  CHAMELEON:
    name: dataset.data_val.test_dataset
    params:
      image_root: 'media/dataset/COD10K/TestDataset/CHAMELEON/Image/'
      gt_root: 'media/dataset/COD10K/TestDataset/CHAMELEON/GT/'
      testsize: 352
  NC4K:
    name: dataset.data_val.test_dataset
    params:
      image_root: 'media/dataset/COD10K/TestDataset/NC4K/Image/'
      gt_root: 'media/dataset/COD10K/TestDataset/NC4K/GT/'
      testsize: 352
  CDS2K:
    name: dataset.cds2k_dataset.cds2K_dataset
    params:
      root: 'media/dataset/CDS2K'
      testsize: 352